export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: 'category/FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCES: 'category/FETCH_CATEGORIES_START_SUCCES',
  FETCH_CATEGORIES_FAILED: 'category/FETCH_CATEGORIES_START_FAILED',
};
